export const s = {
  heading: {
    fontSize: 26,
    fontWeight: 800,
    color: "#1a1209",
    marginBottom: 28,
  },
  form: {
    background: "#fff",
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    marginBottom: 32,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  formTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#1a1209",
    marginBottom: 4,
  },
  row: { display: "flex", gap: 12 },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1.5px solid #e2e8f0",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1.5px solid #e2e8f0",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
    height: 80,
    resize: "vertical",
  },
  formButtons: { display: "flex", gap: 10 },
  btnPrimary: {
    background: "#e83e0b",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 22px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    flex: 1,
  },
  btnCancel: {
    background: "#f1f5f9",
    color: "#475569",
    border: "none",
    borderRadius: 8,
    padding: "10px 18px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  btnEdit: {
    background: "#eff6ff",
    color: "#2563eb",
    border: "none",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnDelete: {
    background: "#fff1f2",
    color: "#e11d48",
    border: "none",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  table: {
    background: "#fff",
    borderRadius: 16,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    overflow: "hidden",
  },
  tableHead: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "12px 20px",
    background: "#f8f7f4",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#94a3b8",
    borderBottom: "1px solid #f1f5f9",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "16px 20px",
    borderBottom: "1px solid #f8f7f4",
    fontSize: 14,
  },
  tag: {
    background: "#f1f5f9",
    color: "#475569",
    borderRadius: 99,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  empty: { textAlign: "center", color: "#94a3b8", padding: "40px 0" },
  tableWrapper: {
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
    borderRadius: 16,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  table: {
    background: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    minWidth: 600,
  },
};
